### ISSUE TITLE
DS Build is broken

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3311]
New unseen error, occurring in `ds build` as of Tuesday afternoon 11/4

cap aborted!
SSHKit::Command::Failed: cd '/var/www/beta.dosomething.org/releases/20141104201434'; /var/www/beta.dosomething.org/releases/20141104201434/bin/ds build stdout: Nothing written
cd '/var/www/beta.dosomething.org/releases/20141104201434'; /var/www/beta.dosomething.org/releases/20141104201434/bin/ds build stderr: Nothing written
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/command.rb:94:in `exit_status='
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:142:in`block (4 levels) in _execute'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:551:in `call'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:551:in`do_request'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:561:in `channel_request'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:465:in`dispatch_incoming_packets'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:205:in`process'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in`loop'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:269:in`wait'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:164:in `block (2 levels) in _execute'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:514:in`call'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:545:in`channel_open_confirmation'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:221:in`preprocess'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:205:in `process'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in`block in loop'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in`loop'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:166:in `block in _execute'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:123:in`tap'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:123:in `_execute'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:66:in`execute'
/var/lib/jenkins/jobs/Beta-Deploy/workspace/config/tasks/default.cap:8:in `block (3 levels) in <top (required)>'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in`instance_exec'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `run'
/var/lib/jenkins/.rvm/gems/ruby-2.0.0-p195/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:12:in`block (2 levels) in execute'
Tasks: TOP => deploy:build
(See full trace by running task with --trace)
The deploy has failed with an error: #<SSHKit::Command::Failed: cd '/var/www/beta.dosomething.org/releases/20141104201434'; /var/www/beta.dosomething.org/releases/20141104201434/bin/ds build stdout: Nothing written
cd '/va

**Comment by aaronschachter** [comment]
@sergii-tkachenko 's eagle eyes have spotted that builds seem to have started failing as a result of:

```
DEBUG [d2af4c31]    Unable to download spyc from                                         [error]
DEBUG [d2af4c31]    https://raw2.github.com/mustangostang/spyc/master/Spyc.php.
```

which is grabbed automatically by including Services in our make file.

**Comment by aaronschachter** [comment]
Confirmed that commenting out Services from the make file runs a `ds build` successfully, locally:

```
; Services
; projects[services][version] = "3.10"
; projects[services][subdir] = "contrib"
```

**Comment by aaronschachter** [comment]
Per @sergii-tkachenko  -- This may have been caused because of https://github.com/blog/1917-github-pages-legacy-ip-deprecation
